name: mVote
version: '1.0'
main: com.mVote.Main
api-version: '1.21'
authors: [BerkKrkmz]
description: Berk korkmaz taraf覺ndan sevgiyle :)
website: berkkorkmaz.com.tr
depend:
  - Votifier
commands:
  mvote:
    description: Ana yonetim komutu
    usage: /mvote <reload>
permissions:
  mvote.bypass:
    description: K覺s覺tlamalar覺 bypass etme izni
    default: op
  mvote.admin:
    description: /mvote komutunu kullanma izni
    default: op